version: "3.8"
services:
  db:
    container_name: db # Because Docker container names must be unique, you cannot scale a service beyond 1 container if you have specified a custom name
    image: mysql:8
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    networks:
      - network1

networks:
  network1:
    name: backend_network

